version: 2
jobs:
  build_on_linux:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run:
          name: Bootstrap dev utilities
          command: bash -e install/bootstrap-posix-dev-utils.sh
  build_on_macos:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run:
          name: Bootstrap dev utilities
          command: bash -e install/bootstrap-posix-dev-utils.sh
workflows:
  version: 2
  build_all_platforms:
    jobs:
      - build_on_linux
      - build_on_macos
