version: 2
jobs:
  shellcheck:
    docker:
      - image: nlknguyen/alpine-shellcheck:latest
    steps:
      - checkout
      - run:
          name: Lint bootstrap bash script
          command: shellcheck install/bootstrap-posix-dev-utils.sh
  build_on_linux:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run:
          name: Bootstrap dev utilities
          command: bash -e install/bootstrap-posix-dev-utils.sh
  build_on_macos:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run:
          name: Bootstrap dev utilities
          command: bash -e install/bootstrap-posix-dev-utils.sh
workflows:
  version: 2
  workflow:
    jobs:
      - shellcheck
      - build_on_linux:
          requires:
            - shellcheck
      - build_on_macos
