version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - checkout
      - run:
          name: Bootstrap dev utilities
          command: bash -e install/bootstrap-posix-dev-utils.sh
